apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-admin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-admin
  template:
    metadata:
      labels:
        app: ui-admin
    spec:
      containers:
      - name: ui-admin
        image: webtruyenacr2855.azurecr.io/ui-admin:latest
        ports:
        - containerPort: 3000