apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui-admin
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /admin(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: ui-admin
            port:
              number: 3000
