apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-main
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-main
  template:
    metadata:
      labels:
        app: ui-main
    spec:
      containers:
      - name: ui-main
        image: webtruyenacr2855.azurecr.io/ui-main:2cdcf871d5f9bb8eea63b6d6751a373a69dca1e3
        ports:
        - containerPort: 3000
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "3000"
        - name: VITE_API_BASE_URL
          value: "http://api-datatruyen.default.svc.cluster.local/api/datatruyen/"
        - name: VITE_OTRUYEN_API_BASE_URL
          value: "http://api-datatruyen.default.svc.cluster.local/api/otruyen/"
        - name: VITE_APP_ENV
          value: "development"
