apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-main
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui-main
  template:
    metadata:
      labels:
        app: ui-main
    spec:
      containers:
      - name: ui-main
        image: webtruyenacr2855.azurecr.io/ui-main:2cdcf871d5f9bb8eea63b6d6751a373a69dca1e3
        ports:
        - containerPort: 3000