apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-main
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui-main
  template:
    metadata:
      labels:
        app: ui-main
    spec:
      containers:
      - name: ui-main
        image: webtruyenacr2855.azurecr.io/ui-main:b772ae6ba64ad730ceec45795b9d821b996e4c9a
        ports:
        - containerPort: 3000
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "3000"
        - name: VITE_API_BASE_URL
          value: "http://4.230.96.180/api/datatruyen/"
        - name: VITE_OTRUYEN_API_BASE_URL
          value: "http://4.230.96.180/api/otruyen/"
        - name: VITE_APP_ENV
          value: "development"
