apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-otruyen
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-otruyen
  template:
    metadata:
      labels:
        app: api-otruyen
    spec:
      containers:
      - name: api-otruyen
        image: webtruyenacr2855.azurecr.io/api-otruyen:d39ba7cf9dd9fae20acdaed0989841b229e505a3
        ports:
        - containerPort: 8001