apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-otruyen
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # --- ADD THIS LINE BELOW ---
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "/api/otruyen"
    # ---------------------------
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/otruyen(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: api-otruyen
            port:
              number: 8001
